spring:

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  h2-console:
    settings:
      web-allow-others: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
        show_sql: true

logging:
  level:
    org:
      hibernate.sql: debug
